### ISSUE TITLE
Simplify CSS for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [ajoeman/prj-rev-bwfs-dasmoto#6]
You did a great job simplifying the CSS code by applying the font-family property to the html selector. Try to also simplify it for other shared properties, such as the font-weight property. Here is how you might apply this,

```css
h1, .price {
  font-weight: bold;
}
```
